server:
  port : 8080

spring:
  datasource:
    url: jdbc:sqlserver://xrpltools-mssql-server.database.windows.net:1433;database=xrpltools-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: xrpltoolsdbuser
    password: Pass1word
  task:
    scheduling:
      pool:
        size: 10
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false

web-ui: https://xrpltoolsadmin.github.io/
web-ui-test: https://xrpltoolstest.github.io/
web-ui-main: https://xrpltools.com/

web-push:
  privateKey: rrRSoa1wkRRl1uSNlWXHsXIxR36yvtFpZwbWWAE8VL8
  publicKey: BI4ApzTJzQKQC2uVI612iX5lP6cvIZFZZVOGFBXwCzPwovkwvp3B4_LwsybRSpLHGs402AMd1yvMSpKNwEW143Y



#spring:
#  datasource:
#    url: jdbc:mysql://20.127.73.70:3306/xrpltools?autoReconnect=true
#    username: xrpldbuser
#    password: Pass1word
#    max-lifetime: 600000
#  task:
#    scheduling:
#      pool:
#        size: 10
#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: false
#    database: mysql