server:
  port : 8081

spring:
  datasource:
    #url: jdbc:mysql://192.168.20.242:3306/xrpltools
    url: jdbc:mysql://localhost:3306/xrpltools
    username: xrpltools
    password: xrpltools
    max-lifetime: 600000
  task:
    scheduling:
      pool:
        size: 10
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    database: mysql

web-ui: http://localhost:9527/
web-ui-test: http://localhost:9528/
web-ui-main: http://localhost:9528/

web-push:
  privateKey: BSjgeevmJB4iUTk9kCVF08GCfd452Oc7YnFOkR81TrI
  publicKey: BKhNjcvSTGrFHiclLDXJm7ZZHb99wALefc2Ja1XlMuPYMSFjNaNgQAU-cowO7fAjikxAnqTR1R6PvC1p8J5cQ48