server:
  port : 8080

spring:
  datasource:
    url: jdbc:sqlserver://xrpltools-mssql-server.database.windows.net:1433;database=xrpltools-db;encrypt=true;trustServerCertificate=false;hostNameInCertificate=*.database.windows.net;loginTimeout=30;
    username: xrpltoolsdbuser
    password: Pass1word
  task:
    scheduling:
      pool:
        size: 10
  jpa:
    hibernate:
      ddl-auto: update
      dialect: org.hibernate.dialect.SQLServer2012Dialect
    show-sql: false

web-ui: https://xrpltoolsadmin.github.io/
web-ui-main: https://xrpltools.com/

web-push:
  privateKey: rrRSoa1wkRRl1uSNlWXHsXIxR36yvtFpZwbWWAE8VL8
  publicKey: BI4ApzTJzQKQC2uVI612iX5lP6cvIZFZZVOGFBXwCzPwovkwvp3B4_LwsybRSpLHGs402AMd1yvMSpKNwEW143Y

discord:
  guildId: 942151807239602198
  bot:
    id: 948239992025673940
    apiKey: OTQ4MjM5OTkyMDI1NjczOTQw.Yh47Tw.MMh8Ne4fTvGXRahbpQgTcR-Hez4
  channels:
    new-airdrop-channel: 942185180528009227
  stats:
    xrp-price-voice-channel: 948235991745986621

twitter:
  auth:
    secretKey: TNVBcZyjQ0vMVSgVjlVt1xTOMJq9Xh5GmrdLKomFnAiHIm47Gz #TODO: Change from Test